### ISSUE TITLE
Adapting this template for a submodule'd library

### ISSUE THREAD

**Issue by NickDarvey** [Mizux/dotnet-native#7]
I'm trying to write bindings for a C/C++ library which I don't control. I've included that library, as is, as a submodule in [this repo](https://github.com/NickDarvey/whisper.dotnet).

I'm trying to adapt this template so that the bindings can be a sibling of the library folder, rather than a child (so it works with a submodule). That is:
```
this template:
├─ Foo/
│  ├─ CMakeLists.txt
│  ├─ dotnet/
│  │  ├─ CMakeLists.txt

mine:
├─ Foo/
│  ├─ CMakeLists.txt
├─ Foo.dotnet/
│  ├─ CMakeLists.txt
```

Right now, it's failing because the swig-generated wrapper doesn't have access to the header file.

```
[build] C:\whisper.dotnet\build\dotnet\NickDarvey.Whisper\Whisper\whisperCSHARP_wrap.cxx(766,10): fatal  error C1083: Cannot open include file: 'whisper.cpp/whisper.h': No such file or directory [C:\whisper.dotnet\build\whisper.cpp.dotnet\dotnet_whisper.vcxproj]
```

When I build _this_ (mizux/dotnet-native) repo with Visual Studio 2022 kit selected it generates a ``build\Foo\dotnet\dotnet_Foo.vcxproj`` which has:

1. The include folder (containing the header) as an `AdditionalIncludeDirectories`
    ```
    <AdditionalIncludeDirectories>C:\dotnet-native\Foo\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    ```
2. The includes folder as an argument to `swig.exe`
    ```
    [...]swig.exe -csharp -IC:/dotnet-native -IC:/dotnet-native/dotnet -IC:/dotnet-native/Foo/include -namespace Mizux.DotnetNative.Foo -dllimport mizux-dotnetnative-native -outdir C:/dotnet-native/build/dotnet/Mizux.DotnetNative/Foo -c++ -o C:/dotnet-native/build/dotnet/Mizux.DotnetNative/Foo/fooCSHARP_wrap.cxx C:/dotnet-native/Foo/dotnet/foo.i
    ```

When I (attempt) to build my (nickdarvey/whisper.dotnet) it generates a vcxproj which _has neither_ of those. I think that's why I'm getting that error.

Are you able to help me get the location of my header files, `./whisper.cpp`, to appear in `AdditionalIncludeDirectories`?

**Comment by Mizux** [comment]
I think you are wrong in the sense this is the C++ wrapper which need the whisper.h file while your are tweaking the C# .csproj project file ?
If I were you, I would try instead to add whisper as a depedency  here:
https://github.com/Mizux/dotnet-native/blob/0994661f8ab5fb62e4c96fcd57e030cc12f6f137/Foo/dotnet/CMakeLists.txt#L15
(simply add it at the end or duplicate this line and adapt, it will be append to the dependency list)

**Comment by NickDarvey** [comment]
Thank you, that helped
